// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.ActionType in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class ActionType(
  override val `value`: Int,
) : WireEnum {
  ACTION_TYPE_UNSPECIFIED(0),
  NAVIGATE(1),
  DEEP_LINK(2),
  OPEN_URL(3),
  CUSTOM(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ActionType> = object : EnumAdapter<ActionType>(
      ActionType::class, 
      PROTO_3, 
      ActionType.ACTION_TYPE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ActionType? = ActionType.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ActionType? = when (value) {
      0 -> ACTION_TYPE_UNSPECIFIED
      1 -> NAVIGATE
      2 -> DEEP_LINK
      3 -> OPEN_URL
      4 -> CUSTOM
      else -> null
    }
  }
}
