// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.BoxAlignment in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class BoxAlignment(
  override val `value`: Int,
) : WireEnum {
  BOX_ALIGNMENT_UNSPECIFIED(0),
  TOP_START(1),
  TOP_CENTER(2),
  TOP_END(3),
  CENTER_START(4),
  CENTER(5),
  CENTER_END(6),
  BOTTOM_START(7),
  BOTTOM_CENTER(8),
  BOTTOM_END(9),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BoxAlignment> = object : EnumAdapter<BoxAlignment>(
      BoxAlignment::class, 
      PROTO_3, 
      BoxAlignment.BOX_ALIGNMENT_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): BoxAlignment? = BoxAlignment.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): BoxAlignment? = when (value) {
      0 -> BOX_ALIGNMENT_UNSPECIFIED
      1 -> TOP_START
      2 -> TOP_CENTER
      3 -> TOP_END
      4 -> CENTER_START
      5 -> CENTER
      6 -> CENTER_END
      7 -> BOTTOM_START
      8 -> BOTTOM_CENTER
      9 -> BOTTOM_END
      else -> null
    }
  }
}
