// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.ButtonStyle in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class ButtonStyle(
  override val `value`: Int,
) : WireEnum {
  BUTTON_STYLE_UNSPECIFIED(0),
  FILLED(1),
  OUTLINED(2),
  TEXT(3),
  ELEVATED(4),
  FILLED_TONAL(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ButtonStyle> = object : EnumAdapter<ButtonStyle>(
      ButtonStyle::class, 
      PROTO_3, 
      ButtonStyle.BUTTON_STYLE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ButtonStyle? = ButtonStyle.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ButtonStyle? = when (value) {
      0 -> BUTTON_STYLE_UNSPECIFIED
      1 -> FILLED
      2 -> OUTLINED
      3 -> TEXT
      4 -> ELEVATED
      5 -> FILLED_TONAL
      else -> null
    }
  }
}
