// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.CardShape in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class CardShape(
  override val `value`: Int,
) : WireEnum {
  CARD_SHAPE_UNSPECIFIED(0),
  CARD_ROUNDED4(1),
  CARD_ROUNDED8(2),
  CARD_ROUNDED12(3),
  CARD_ROUNDED16(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CardShape> = object : EnumAdapter<CardShape>(
      CardShape::class, 
      PROTO_3, 
      CardShape.CARD_SHAPE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): CardShape? = CardShape.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): CardShape? = when (value) {
      0 -> CARD_SHAPE_UNSPECIFIED
      1 -> CARD_ROUNDED4
      2 -> CARD_ROUNDED8
      3 -> CARD_ROUNDED12
      4 -> CARD_ROUNDED16
      else -> null
    }
  }
}
