// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.ClipShape in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class ClipShape(
  override val `value`: Int,
) : WireEnum {
  CLIP_SHAPE_UNSPECIFIED(0),
  CIRCLE(1),
  ROUNDED4(2),
  ROUNDED8(3),
  ROUNDED12(4),
  ROUNDED16(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ClipShape> = object : EnumAdapter<ClipShape>(
      ClipShape::class, 
      PROTO_3, 
      ClipShape.CLIP_SHAPE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ClipShape? = ClipShape.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ClipShape? = when (value) {
      0 -> CLIP_SHAPE_UNSPECIFIED
      1 -> CIRCLE
      2 -> ROUNDED4
      3 -> ROUNDED8
      4 -> ROUNDED12
      5 -> ROUNDED16
      else -> null
    }
  }
}
