// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.ContentScale in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class ContentScale(
  override val `value`: Int,
) : WireEnum {
  CONTENT_SCALE_UNSPECIFIED(0),
  FILL_WIDTH(1),
  FILL_HEIGHT(2),
  CROP(3),
  INSIDE(4),
  FIT(5),
  FILL_BOUNDS(6),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ContentScale> = object : EnumAdapter<ContentScale>(
      ContentScale::class, 
      PROTO_3, 
      ContentScale.CONTENT_SCALE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ContentScale? = ContentScale.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ContentScale? = when (value) {
      0 -> CONTENT_SCALE_UNSPECIFIED
      1 -> FILL_WIDTH
      2 -> FILL_HEIGHT
      3 -> CROP
      4 -> INSIDE
      5 -> FIT
      6 -> FILL_BOUNDS
      else -> null
    }
  }
}
