// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.DividerToken in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class DividerToken(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val version: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.baksha97.sdui.schema.A11y#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val a11y: A11y? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val thickness: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.baksha97.sdui.schema.ColorValue#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val color: ColorValue? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.baksha97.sdui.schema.Margin#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val margin: Margin? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DividerToken, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DividerToken) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (version != other.version) return false
    if (a11y != other.a11y) return false
    if (thickness != other.thickness) return false
    if (color != other.color) return false
    if (margin != other.margin) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + (a11y?.hashCode() ?: 0)
      result = result * 37 + thickness.hashCode()
      result = result * 37 + (color?.hashCode() ?: 0)
      result = result * 37 + (margin?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """version=$version"""
    if (a11y != null) result += """a11y=$a11y"""
    result += """thickness=$thickness"""
    if (color != null) result += """color=$color"""
    if (margin != null) result += """margin=$margin"""
    return result.joinToString(prefix = "DividerToken{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    version: Int = this.version,
    a11y: A11y? = this.a11y,
    thickness: Int = this.thickness,
    color: ColorValue? = this.color,
    margin: Margin? = this.margin,
    unknownFields: ByteString = this.unknownFields,
  ): DividerToken = DividerToken(id, version, a11y, thickness, color, margin, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DividerToken> = object : ProtoAdapter<DividerToken>(
      FieldEncoding.LENGTH_DELIMITED, 
      DividerToken::class, 
      "type.googleapis.com/com.baksha97.sdui.schema.DividerToken", 
      PROTO_3, 
      null, 
      "sdui.proto"
    ) {
      override fun encodedSize(`value`: DividerToken): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        if (value.version != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.version)
        if (value.a11y != null) size += A11y.ADAPTER.encodedSizeWithTag(3, value.a11y)
        if (value.thickness != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.thickness)
        if (value.color != null) size += ColorValue.ADAPTER.encodedSizeWithTag(5, value.color)
        if (value.margin != null) size += Margin.ADAPTER.encodedSizeWithTag(6, value.margin)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DividerToken) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.version)
        if (value.a11y != null) A11y.ADAPTER.encodeWithTag(writer, 3, value.a11y)
        if (value.thickness != 0) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.thickness)
        if (value.color != null) ColorValue.ADAPTER.encodeWithTag(writer, 5, value.color)
        if (value.margin != null) Margin.ADAPTER.encodeWithTag(writer, 6, value.margin)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DividerToken) {
        writer.writeBytes(value.unknownFields)
        if (value.margin != null) Margin.ADAPTER.encodeWithTag(writer, 6, value.margin)
        if (value.color != null) ColorValue.ADAPTER.encodeWithTag(writer, 5, value.color)
        if (value.thickness != 0) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.thickness)
        if (value.a11y != null) A11y.ADAPTER.encodeWithTag(writer, 3, value.a11y)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.version)
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
      }

      override fun decode(reader: ProtoReader): DividerToken {
        var id: String = ""
        var version: Int = 0
        var a11y: A11y? = null
        var thickness: Int = 0
        var color: ColorValue? = null
        var margin: Margin? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> version = ProtoAdapter.INT32.decode(reader)
            3 -> a11y = A11y.ADAPTER.decode(reader)
            4 -> thickness = ProtoAdapter.INT32.decode(reader)
            5 -> color = ColorValue.ADAPTER.decode(reader)
            6 -> margin = Margin.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DividerToken(
          id = id,
          version = version,
          a11y = a11y,
          thickness = thickness,
          color = color,
          margin = margin,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DividerToken): DividerToken = value.copy(
        a11y = value.a11y?.let(A11y.ADAPTER::redact),
        color = value.color?.let(ColorValue.ADAPTER::redact),
        margin = value.margin?.let(Margin.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
