// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.HorizontalAlignment in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class HorizontalAlignment(
  override val `value`: Int,
) : WireEnum {
  HORIZONTAL_ALIGNMENT_UNSPECIFIED(0),
  START(1),
  CENTER_HORIZONTALLY(2),
  END(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HorizontalAlignment> = object :
        EnumAdapter<HorizontalAlignment>(
      HorizontalAlignment::class, 
      PROTO_3, 
      HorizontalAlignment.HORIZONTAL_ALIGNMENT_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): HorizontalAlignment? =
          HorizontalAlignment.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): HorizontalAlignment? = when (value) {
      0 -> HORIZONTAL_ALIGNMENT_UNSPECIFIED
      1 -> START
      2 -> CENTER_HORIZONTALLY
      3 -> END
      else -> null
    }
  }
}
