// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.LiveRegion in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class LiveRegion(
  override val `value`: Int,
) : WireEnum {
  LIVE_REGION_UNSPECIFIED(0),
  OFF(1),
  POLITE(2),
  ASSERTIVE(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LiveRegion> = object : EnumAdapter<LiveRegion>(
      LiveRegion::class, 
      PROTO_3, 
      LiveRegion.LIVE_REGION_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): LiveRegion? = LiveRegion.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): LiveRegion? = when (value) {
      0 -> LIVE_REGION_UNSPECIFIED
      1 -> OFF
      2 -> POLITE
      3 -> ASSERTIVE
      else -> null
    }
  }
}
