// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.Role in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

/**
 * Enums
 */
public enum class Role(
  override val `value`: Int,
) : WireEnum {
  ROLE_UNSPECIFIED(0),
  BANNER(1),
  IMAGE(2),
  BUTTON(3),
  CHECKBOX(4),
  HEADER(5),
  LINK(6),
  SWITCH(7),
  TEXT_FIELD(8),
  SLIDER(9),
  PROGRESS_BAR(10),
  RADIO_BUTTON(11),
  NONE(12),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Role> = object : EnumAdapter<Role>(
      Role::class, 
      PROTO_3, 
      Role.ROLE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): Role? = Role.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Role? = when (value) {
      0 -> ROLE_UNSPECIFIED
      1 -> BANNER
      2 -> IMAGE
      3 -> BUTTON
      4 -> CHECKBOX
      5 -> HEADER
      6 -> LINK
      7 -> SWITCH
      8 -> TEXT_FIELD
      9 -> SLIDER
      10 -> PROGRESS_BAR
      11 -> RADIO_BUTTON
      12 -> NONE
      else -> null
    }
  }
}
