// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.ScreenPayload in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

public class ScreenPayload(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  tokens: List<TokenRef> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ScreenPayload, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.baksha97.sdui.schema.TokenRef#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val tokens: List<TokenRef> = immutableCopyOf("tokens", tokens)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ScreenPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (tokens != other.tokens) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + tokens.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (tokens.isNotEmpty()) result += """tokens=$tokens"""
    return result.joinToString(prefix = "ScreenPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    tokens: List<TokenRef> = this.tokens,
    unknownFields: ByteString = this.unknownFields,
  ): ScreenPayload = ScreenPayload(id, tokens, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ScreenPayload> = object : ProtoAdapter<ScreenPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      ScreenPayload::class, 
      "type.googleapis.com/com.baksha97.sdui.schema.ScreenPayload", 
      PROTO_3, 
      null, 
      "sdui.proto"
    ) {
      override fun encodedSize(`value`: ScreenPayload): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        size += TokenRef.ADAPTER.asRepeated().encodedSizeWithTag(2, value.tokens)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ScreenPayload) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        TokenRef.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.tokens)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ScreenPayload) {
        writer.writeBytes(value.unknownFields)
        TokenRef.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.tokens)
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
      }

      override fun decode(reader: ProtoReader): ScreenPayload {
        var id: String = ""
        val tokens = mutableListOf<TokenRef>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> tokens.add(TokenRef.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ScreenPayload(
          id = id,
          tokens = tokens,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ScreenPayload): ScreenPayload = value.copy(
        tokens = value.tokens.redactElements(TokenRef.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
