// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.SliderToken in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class SliderToken(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val version: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.baksha97.sdui.schema.A11y#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val a11y: A11y? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "initialValue",
    schemaIndex = 3,
  )
  public val initial_value: Float = 0f,
  @field:WireField(
    tag = 5,
    adapter = "com.baksha97.sdui.schema.FloatRange#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "valueRange",
    schemaIndex = 4,
  )
  public val value_range: FloatRange? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val steps: Int = 0,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val enabled: Boolean = false,
  @field:WireField(
    tag = 8,
    adapter = "com.baksha97.sdui.schema.Margin#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val margin: Margin? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.baksha97.sdui.schema.Action#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "onChange",
    schemaIndex = 8,
  )
  public val on_change: Action? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SliderToken, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SliderToken) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (version != other.version) return false
    if (a11y != other.a11y) return false
    if (initial_value != other.initial_value) return false
    if (value_range != other.value_range) return false
    if (steps != other.steps) return false
    if (enabled != other.enabled) return false
    if (margin != other.margin) return false
    if (on_change != other.on_change) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + (a11y?.hashCode() ?: 0)
      result = result * 37 + initial_value.hashCode()
      result = result * 37 + (value_range?.hashCode() ?: 0)
      result = result * 37 + steps.hashCode()
      result = result * 37 + enabled.hashCode()
      result = result * 37 + (margin?.hashCode() ?: 0)
      result = result * 37 + (on_change?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """version=$version"""
    if (a11y != null) result += """a11y=$a11y"""
    result += """initial_value=$initial_value"""
    if (value_range != null) result += """value_range=$value_range"""
    result += """steps=$steps"""
    result += """enabled=$enabled"""
    if (margin != null) result += """margin=$margin"""
    if (on_change != null) result += """on_change=$on_change"""
    return result.joinToString(prefix = "SliderToken{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    version: Int = this.version,
    a11y: A11y? = this.a11y,
    initial_value: Float = this.initial_value,
    value_range: FloatRange? = this.value_range,
    steps: Int = this.steps,
    enabled: Boolean = this.enabled,
    margin: Margin? = this.margin,
    on_change: Action? = this.on_change,
    unknownFields: ByteString = this.unknownFields,
  ): SliderToken = SliderToken(id, version, a11y, initial_value, value_range, steps, enabled,
      margin, on_change, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SliderToken> = object : ProtoAdapter<SliderToken>(
      FieldEncoding.LENGTH_DELIMITED, 
      SliderToken::class, 
      "type.googleapis.com/com.baksha97.sdui.schema.SliderToken", 
      PROTO_3, 
      null, 
      "sdui.proto"
    ) {
      override fun encodedSize(`value`: SliderToken): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        if (value.version != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.version)
        if (value.a11y != null) size += A11y.ADAPTER.encodedSizeWithTag(3, value.a11y)
        if (!value.initial_value.equals(0f)) size += ProtoAdapter.FLOAT.encodedSizeWithTag(4,
            value.initial_value)
        if (value.value_range != null) size += FloatRange.ADAPTER.encodedSizeWithTag(5,
            value.value_range)
        if (value.steps != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.steps)
        if (value.enabled != false) size += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.enabled)
        if (value.margin != null) size += Margin.ADAPTER.encodedSizeWithTag(8, value.margin)
        if (value.on_change != null) size += Action.ADAPTER.encodedSizeWithTag(9, value.on_change)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SliderToken) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.version)
        if (value.a11y != null) A11y.ADAPTER.encodeWithTag(writer, 3, value.a11y)
        if (!value.initial_value.equals(0f)) ProtoAdapter.FLOAT.encodeWithTag(writer, 4,
            value.initial_value)
        if (value.value_range != null) FloatRange.ADAPTER.encodeWithTag(writer, 5,
            value.value_range)
        if (value.steps != 0) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.steps)
        if (value.enabled != false) ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.enabled)
        if (value.margin != null) Margin.ADAPTER.encodeWithTag(writer, 8, value.margin)
        if (value.on_change != null) Action.ADAPTER.encodeWithTag(writer, 9, value.on_change)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SliderToken) {
        writer.writeBytes(value.unknownFields)
        if (value.on_change != null) Action.ADAPTER.encodeWithTag(writer, 9, value.on_change)
        if (value.margin != null) Margin.ADAPTER.encodeWithTag(writer, 8, value.margin)
        if (value.enabled != false) ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.enabled)
        if (value.steps != 0) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.steps)
        if (value.value_range != null) FloatRange.ADAPTER.encodeWithTag(writer, 5,
            value.value_range)
        if (!value.initial_value.equals(0f)) ProtoAdapter.FLOAT.encodeWithTag(writer, 4,
            value.initial_value)
        if (value.a11y != null) A11y.ADAPTER.encodeWithTag(writer, 3, value.a11y)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.version)
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
      }

      override fun decode(reader: ProtoReader): SliderToken {
        var id: String = ""
        var version: Int = 0
        var a11y: A11y? = null
        var initial_value: Float = 0f
        var value_range: FloatRange? = null
        var steps: Int = 0
        var enabled: Boolean = false
        var margin: Margin? = null
        var on_change: Action? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> version = ProtoAdapter.INT32.decode(reader)
            3 -> a11y = A11y.ADAPTER.decode(reader)
            4 -> initial_value = ProtoAdapter.FLOAT.decode(reader)
            5 -> value_range = FloatRange.ADAPTER.decode(reader)
            6 -> steps = ProtoAdapter.INT32.decode(reader)
            7 -> enabled = ProtoAdapter.BOOL.decode(reader)
            8 -> margin = Margin.ADAPTER.decode(reader)
            9 -> on_change = Action.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SliderToken(
          id = id,
          version = version,
          a11y = a11y,
          initial_value = initial_value,
          value_range = value_range,
          steps = steps,
          enabled = enabled,
          margin = margin,
          on_change = on_change,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SliderToken): SliderToken = value.copy(
        a11y = value.a11y?.let(A11y.ADAPTER::redact),
        value_range = value.value_range?.let(FloatRange.ADAPTER::redact),
        margin = value.margin?.let(Margin.ADAPTER::redact),
        on_change = value.on_change?.let(Action.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
