// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.TemplateString in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class TemplateString(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val raw: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TemplateString, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TemplateString) return false
    if (unknownFields != other.unknownFields) return false
    if (raw != other.raw) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + raw.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """raw=${sanitize(raw)}"""
    return result.joinToString(prefix = "TemplateString{", separator = ", ", postfix = "}")
  }

  public fun copy(raw: String = this.raw, unknownFields: ByteString = this.unknownFields):
      TemplateString = TemplateString(raw, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TemplateString> = object : ProtoAdapter<TemplateString>(
      FieldEncoding.LENGTH_DELIMITED, 
      TemplateString::class, 
      "type.googleapis.com/com.baksha97.sdui.schema.TemplateString", 
      PROTO_3, 
      null, 
      "sdui.proto"
    ) {
      override fun encodedSize(`value`: TemplateString): Int {
        var size = value.unknownFields.size
        if (value.raw != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.raw)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TemplateString) {
        if (value.raw != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.raw)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TemplateString) {
        writer.writeBytes(value.unknownFields)
        if (value.raw != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.raw)
      }

      override fun decode(reader: ProtoReader): TemplateString {
        var raw: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> raw = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TemplateString(
          raw = raw,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TemplateString): TemplateString = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
