// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.TextAlignValue in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class TextAlignValue(
  override val `value`: Int,
) : WireEnum {
  TEXT_ALIGN_UNSPECIFIED(0),
  TEXT_START(1),
  TEXT_CENTER(2),
  TEXT_END(3),
  JUSTIFY(4),
  LEFT(5),
  RIGHT(6),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextAlignValue> = object : EnumAdapter<TextAlignValue>(
      TextAlignValue::class, 
      PROTO_3, 
      TextAlignValue.TEXT_ALIGN_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): TextAlignValue? = TextAlignValue.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TextAlignValue? = when (value) {
      0 -> TEXT_ALIGN_UNSPECIFIED
      1 -> TEXT_START
      2 -> TEXT_CENTER
      3 -> TEXT_END
      4 -> JUSTIFY
      5 -> LEFT
      6 -> RIGHT
      else -> null
    }
  }
}
