// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.TextStyle in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class TextStyle(
  override val `value`: Int,
) : WireEnum {
  TEXT_STYLE_UNSPECIFIED(0),
  DISPLAY_LARGE(1),
  DISPLAY_MEDIUM(2),
  DISPLAY_SMALL(3),
  HEADLINE_LARGE(4),
  HEADLINE_MEDIUM(5),
  HEADLINE_SMALL(6),
  TITLE_LARGE(7),
  TITLE_MEDIUM(8),
  TITLE_SMALL(9),
  BODY_LARGE(10),
  BODY_MEDIUM(11),
  BODY_SMALL(12),
  LABEL_LARGE(13),
  LABEL_MEDIUM(14),
  LABEL_SMALL(15),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextStyle> = object : EnumAdapter<TextStyle>(
      TextStyle::class, 
      PROTO_3, 
      TextStyle.TEXT_STYLE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): TextStyle? = TextStyle.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TextStyle? = when (value) {
      0 -> TEXT_STYLE_UNSPECIFIED
      1 -> DISPLAY_LARGE
      2 -> DISPLAY_MEDIUM
      3 -> DISPLAY_SMALL
      4 -> HEADLINE_LARGE
      5 -> HEADLINE_MEDIUM
      6 -> HEADLINE_SMALL
      7 -> TITLE_LARGE
      8 -> TITLE_MEDIUM
      9 -> TITLE_SMALL
      10 -> BODY_LARGE
      11 -> BODY_MEDIUM
      12 -> BODY_SMALL
      13 -> LABEL_LARGE
      14 -> LABEL_MEDIUM
      15 -> LABEL_SMALL
      else -> null
    }
  }
}
