// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baksha97.sdui.schema.TextOverflowValue in sdui.proto
package com.baksha97.sdui.schema

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class TextOverflowValue(
  override val `value`: Int,
) : WireEnum {
  TEXT_OVERFLOW_UNSPECIFIED(0),
  CLIP(1),
  ELLIPSIS(2),
  VISIBLE(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextOverflowValue> = object : EnumAdapter<TextOverflowValue>(
      TextOverflowValue::class, 
      PROTO_3, 
      TextOverflowValue.TEXT_OVERFLOW_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): TextOverflowValue? = TextOverflowValue.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TextOverflowValue? = when (value) {
      0 -> TEXT_OVERFLOW_UNSPECIFIED
      1 -> CLIP
      2 -> ELLIPSIS
      3 -> VISIBLE
      else -> null
    }
  }
}
